default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "db") %>

development:
  <<: *default
  database: yata_development

test:
  <<: *default
  database: yata_test

production:
  primary:
    <<: *default
    database: yata_production
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>

  cache:
    <<: *default
    database: yata_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: yata_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: yata_production_cable
    migrations_paths: db/cable_migrate
